require('nvim-navic').setup {
    lsp = {
        auto_attach = true,
    },
    highlight = true,
    separator = " > ",
    depth_limit = 0,
    depth_limit_indicator = "..",
    icons = {
        File          = "󰈙 ",
        Module        = " ",
        Namespace     = " ",
        Package       = " ",
        Class         = "󰠱 ",
        Method        = " ",
        Property      = "󰜢 ",
        Field         = "󰜢 ",
        Constructor   = " ",
        Enum          = " ",
        Interface     = " ",
        Function      = "󰊕 ",
        Variable      = "󰀫 ",
        Constant      = "󰏿 ",
        String        = "󰉿 ",
        Number        = " ",
        Boolean       = " ",
        Array         = " ",
        Object        = "󰙅 ",
        Key           = "󰌋 ",
        Null          = "󰟢 ",
        EnumMember    = " ",
        Struct        = "󰙅 ",
        Event         = " ",
        Operator      = "󰆕 ",
        TypeParameter = " ",
    },
    -- Old mappings
    -- icons = {
    --     File          = " ",
    --     Module        = " ",
    --     Namespace     = " ",
    --     Package       = " ",
    --     Class         = " ",
    --     Method        = " ",
    --     Property      = " ",
    --     Field         = " ",
    --     Constructor   = " ",
    --     Enum          = " ",
    --     Interface     = " ",
    --     Function      = "󰊕 ",
    --     Variable      = "󰀫 ",
    --     Constant      = "󰏿 ",
    --     String        = " ",
    --     Number        = " ",
    --     Boolean       = " ",
    --     Array         = " ",
    --     Object        = " ",
    --     Key           = " ",
    --     Null          = "󰟢 ",
    --     EnumMember    = " ",
    --     Struct        = " ",
    --     Event         = " ",
    --     Operator      = " ",
    --     TypeParameter = " ",
    -- },
    -- Below is lsp-kind mappings
    -- symbol_map = {
    --   Text = "󰉿",
    --   Method = "󰆧",
    --   Function = "󰊕",
    --   Constructor = "",
    --   Field = "󰜢",
    --   Variable = "󰀫",
    --   Class = "󰠱",
    --   Interface = "",
    --   Module = "",
    --   Property = "󰜢",
    --   Unit = "󰑭",
    --   Value = "󰎠",
    --   Enum = "",
    --   Keyword = "󰌋",
    --   Snippet = "",
    --   Color = "󰏘",
    --   File = "󰈙",
    --   Reference = "󰈇",
    --   Folder = "󰉋",
    --   EnumMember = "",
    --   Constant = "󰏿",
    --   Struct = "󰙅",
    --   Event = "",
    --   Operator = "󰆕",
    --   TypeParameter = "",
    -- },

}
